#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dataFrameToCsvLines_v2() works", {

  expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = 1)
    # unused argument (... = 1)
  )
   expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = 1:2)
    # unused argument (... = 1:2)
  )
   expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = "a")
    # unused argument (... = "a")
  )
   expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = c("a", "b"))
    # unused argument (... = c("a", "b"))
  )
   expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = TRUE)
    # unused argument (... = TRUE)
  )
   expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = FALSE)
    # unused argument (... = FALSE)
  )
   expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = as.POSIXct("2018-06-03 23:50:00"))
    # unused argument (... = 1528062600)
  )
   expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v2(dframe = 1, ... = list(key = c("a", "b"), value = 1:2))
    # unused argument (... = list(key = c("a", "b"), value = 1:2))
  )

})

