#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-11-01 18:19:55.721139.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("getColClasses2() works", {

  f <- kwb.en13508.2:::getColClasses2

  expect_error(
    f()
    # Argument "codes" fehlt (ohne Standardwert)
  )

})
