#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toEuFormat_v1() works", {

  expect_error(
    kwb.en13508.2:::toEuFormat_v1(header.info = 1, inspections = 1)
    # $ operator is invalid for atomic vectors
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v1(header.info = list(key = c("a", "b"), value = 1:2), inspections = 1)
    # argument "observations" is missing, with no default
  )

})

