#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getValueFromKeyValueString() works", {

  kwb.en13508.2:::getValueFromKeyValueString(keyvalue = "a")
   kwb.en13508.2:::getValueFromKeyValueString(keyvalue = c("a", "b"))
   expect_error(
    kwb.en13508.2:::getValueFromKeyValueString(keyvalue = 1)
    # non-character argument
  )

})

