#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("valuesToCsv() works", {

  kwb.en13508.2:::valuesToCsv(x = 1)
   kwb.en13508.2:::valuesToCsv(x = 1:2)
   kwb.en13508.2:::valuesToCsv(x = "a")
   kwb.en13508.2:::valuesToCsv(x = c("a", "b"))
   kwb.en13508.2:::valuesToCsv(x = TRUE)
   kwb.en13508.2:::valuesToCsv(x = FALSE)
   kwb.en13508.2:::valuesToCsv(x = list(key = c("a", "b"), value = 1:2))
   expect_error(
    kwb.en13508.2:::valuesToCsv(x = as.POSIXct("2018-06-03 23:50:00"))
    # character string is not in a standard unambiguous format
  )

})

