#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_observations() works", {

  expect_error(
    kwb.en13508.2:::get_observations(caption_line = 1, c_body = 1)
    # argument "header_info" is missing, with no default
  )

})

