#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("mergeInspectionBlocks() works", {

  expect_error(
    kwb.en13508.2:::mergeInspectionBlocks(inspectionBlocks = 1)
    # $ operator is invalid for atomic vectors
  )

})

