#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getInspectionHeaderInfo() works", {

  kwb.en13508.2:::getInspectionHeaderInfo(eu_lines = "a")
   kwb.en13508.2:::getInspectionHeaderInfo(eu_lines = c("a", "b"))
  #  expect_error(
  #   kwb.en13508.2:::getInspectionHeaderInfo(eu_lines = 1)
  #   # invalid 'text' argument
  # )

})

