#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("writeEuCodedFile() works", {

  expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = 1, ... = 1)
    # inspection.data is not a list but:
#  num 1
  )
   expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = 1:2, ... = 1)
    # inspection.data is not a list but:
#  int [1:2] 1 2
  )
   expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = "a", ... = 1)
    # inspection.data is not a list but:
#  chr "a"
  )
   expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = c("a", "b"), ... = 1)
    # inspection.data is not a list but:
#  chr [1:2] "a" "b"
  )
   expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = TRUE, ... = 1)
    # inspection.data is not a list but:
#  logi TRUE
  )
   expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = FALSE, ... = 1)
    # inspection.data is not a list but:
#  logi FALSE
  )
   expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = as.POSIXct("2018-06-03 23:50:00"), ... = 1)
    # inspection.data is not a list but:
#  POSIXct[1:1], format: "2018-06-03 23:50:00"
  )
   expect_error(
    kwb.en13508.2:::writeEuCodedFile(inspection.data = list(key = c("a", "b"), value = 1:2), ... = 1)
    # No such list elements: 'header.info'
# Available elements: 'key', 'value'
  )

})

