#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-07-27 07:01:23.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("stopOnInvalidLineDamageCodes() works", {

  expect_error(
    kwb.rerau:::stopOnInvalidLineDamageCodes()
    # argument "J" is missing, with no default
  )

})

