#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("textblockToDataframe() works", {

  expect_error(
    kwb.en13508.2:::textblockToDataframe(textblock = 1, sep = 1)
    # invalid 'text' argument
  )
   expect_error(
    kwb.en13508.2:::textblockToDataframe(textblock = "a", sep = 1)
    # argument "quoteCharacter" is missing, with no default
  )

})

