#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("numberOfInspections() works", {

  expect_error(
    kwb.en13508.2:::numberOfInspections(x = 1)
    # xx is not a list but:
#  num 1
  )
   expect_error(
    kwb.en13508.2:::numberOfInspections(x = 1:2)
    # xx is not a list but:
#  int 1
  )
   expect_error(
    kwb.en13508.2:::numberOfInspections(x = "a")
    # xx is not a list but:
#  chr "a"
  )
   expect_error(
    kwb.en13508.2:::numberOfInspections(x = TRUE)
    # xx is not a list but:
#  logi TRUE
  )
   expect_error(
    kwb.en13508.2:::numberOfInspections(x = FALSE)
    # xx is not a list but:
#  logi FALSE
  )
   expect_error(
    kwb.en13508.2:::numberOfInspections(x = as.POSIXct("2018-06-03 23:50:00"))
    # xx is not a list but:
#  POSIXct[1:1], format: "2018-06-03 23:50:00"
  )
   expect_error(
    kwb.en13508.2:::numberOfInspections(x = list(key = c("a", "b"), value = 1:2))
    # xx is not a list but:
#  chr [1:2] "a" "b"
  )

})

