#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readEuCodedFiles() works", {

   expect_error(
    kwb.en13508.2:::readEuCodedFiles(input.files = 1)
    # a character vector argument expected
  )

})

