#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getHeaderLinesFromHeaderInfo() works", {

  expect_error(
    kwb.en13508.2:::getHeaderLinesFromHeaderInfo(header.info = 1)
    # 6 columns missing in data frame 'header.info': 'encoding', 'language', 'separator', 'decimal', 'quote', 'year'
# Available column: 
  )
   expect_error(
    kwb.en13508.2:::getHeaderLinesFromHeaderInfo(header.info = list(key = c("a", "b"), value = 1:2))
    # 6 columns missing in data frame 'header.info': 'encoding', 'language', 'separator', 'decimal', 'quote', 'year'
# Available columns: 'key', 'value'
  )

})

