#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("cleanDuplicatedColumns() works", {

  kwb.en13508.2:::cleanDuplicatedColumns(x = 1)
   kwb.en13508.2:::cleanDuplicatedColumns(x = 1:2)
   kwb.en13508.2:::cleanDuplicatedColumns(x = "a")
   kwb.en13508.2:::cleanDuplicatedColumns(x = c("a", "b"))
   kwb.en13508.2:::cleanDuplicatedColumns(x = TRUE)
   kwb.en13508.2:::cleanDuplicatedColumns(x = FALSE)
   kwb.en13508.2:::cleanDuplicatedColumns(x = as.POSIXct("2018-06-03 23:50:00"))
   kwb.en13508.2:::cleanDuplicatedColumns(x = list(key = c("a", "b"), value = 1:2))

})

