#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("removeDuplicatedColumns() works", {

  kwb.en13508.2:::removeDuplicatedColumns(x = 1)
   kwb.en13508.2:::removeDuplicatedColumns(x = 1:2)
   kwb.en13508.2:::removeDuplicatedColumns(x = "a")
   kwb.en13508.2:::removeDuplicatedColumns(x = c("a", "b"))
   kwb.en13508.2:::removeDuplicatedColumns(x = TRUE)
   kwb.en13508.2:::removeDuplicatedColumns(x = FALSE)
   kwb.en13508.2:::removeDuplicatedColumns(x = as.POSIXct("2018-06-03 23:50:00"))
   kwb.en13508.2:::removeDuplicatedColumns(x = list(key = c("a", "b"), value = 1:2))

})

