#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("observationHeaderLine() works", {

  kwb.en13508.2:::observationHeaderLine(header.fields = 1, separator = "a")
   kwb.en13508.2:::observationHeaderLine(header.fields = 1, separator = c("a", "b"))
   kwb.en13508.2:::observationHeaderLine(header.fields = 1:2, separator = "a")
   kwb.en13508.2:::observationHeaderLine(header.fields = 1:2, separator = c("a", "b"))
   kwb.en13508.2:::observationHeaderLine(header.fields = "a", separator = "a")
   kwb.en13508.2:::observationHeaderLine(header.fields = "a", separator = c("a", "b"))
   kwb.en13508.2:::observationHeaderLine(header.fields = c("a", "b"), separator = "a")
   kwb.en13508.2:::observationHeaderLine(header.fields = c("a", "b"), separator = c("a", "b"))
   kwb.en13508.2:::observationHeaderLine(header.fields = TRUE, separator = "a")
   kwb.en13508.2:::observationHeaderLine(header.fields = TRUE, separator = c("a", "b"))
   kwb.en13508.2:::observationHeaderLine(header.fields = FALSE, separator = "a")
   kwb.en13508.2:::observationHeaderLine(header.fields = FALSE, separator = c("a", "b"))
   kwb.en13508.2:::observationHeaderLine(header.fields = list(key = c("a", "b"), value = 1:2), separator = "a")
   kwb.en13508.2:::observationHeaderLine(header.fields = list(key = c("a", "b"), value = 1:2), separator = c("a", "b"))
   expect_error(
    kwb.en13508.2:::observationHeaderLine(header.fields = 1, separator = 1)
    # invalid 'collapse' argument
  )
   expect_error(
    kwb.en13508.2:::observationHeaderLine(header.fields = as.POSIXct("2018-06-03 23:50:00"), separator = 1)
    # character string is not in a standard unambiguous format
  )

})

