#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readPackageFile() works", {

  expect_error(
    kwb.en13508.2:::readPackageFile(file = 1, ... = 1)
    # No such file: '1' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes_de.csv'
  )
   expect_error(
    kwb.en13508.2:::readPackageFile(file = 1:2, ... = 1)
    # No such file: '1' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes.csv'
#   'eucodes_de.csv'
#   'eucodes_de.csv'No such file: '2' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes.csv'
#   'eucodes_de.csv'
#   'eucodes_de.csv'
  )
   expect_error(
    kwb.en13508.2:::readPackageFile(file = "a", ... = 1)
    # No such file: 'a' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes_de.csv'
  )
   expect_error(
    kwb.en13508.2:::readPackageFile(file = c("a", "b"), ... = 1)
    # No such file: 'a' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes.csv'
#   'eucodes_de.csv'
#   'eucodes_de.csv'No such file: 'b' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes.csv'
#   'eucodes_de.csv'
#   'eucodes_de.csv'
  )
   expect_error(
    kwb.en13508.2:::readPackageFile(file = TRUE, ... = 1)
    # No such file: 'TRUE' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes_de.csv'
  )
   expect_error(
    kwb.en13508.2:::readPackageFile(file = FALSE, ... = 1)
    # No such file: 'FALSE' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes_de.csv'
  )
   expect_error(
    kwb.en13508.2:::readPackageFile(file = as.POSIXct("2018-06-03 23:50:00"), ... = 1)
    # No such file: '2018-06-03 23:50:00' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes_de.csv'
  )
   expect_error(
    kwb.en13508.2:::readPackageFile(file = list(key = c("a", "b"), value = 1:2), ... = 1)
    # No such file: 'c("a", "b")' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes.csv'
#   'eucodes_de.csv'
#   'eucodes_de.csv'No such file: '1:2' in
#   '/home/hauke/R/i686-pc-linux-gnu-library/3.3/kwb.en13508.2/extdata'.
# Available files:
#   'eucodes.csv'
#   'eucodes.csv'
#   'eucodes_de.csv'
#   'eucodes_de.csv'
  )

})

