#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("extractInspectionBlocks() works", {

  expect_error(
    kwb.en13508.2:::extractInspectionBlocks(eu_lines = 1, headerInfos = 1)
    # $ operator is invalid for atomic vectors
  )

})

