#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("quoteTextIfNeeded() works", {

  expect_error(
    kwb.en13508.2:::quoteTextIfNeeded(x = 1, sep = 1)
    # argument "qchar" is missing, with no default
  )

})

