#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-11-01 18:19:56.0359.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("stop_on_hash_duplicates() works", {

  f <- kwb.en13508.2:::stop_on_hash_duplicates

  expect_error(
    f()
    # Argument "hashes" fehlt (ohne Standardwert)
  )

})
