#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("mergeInspectionData() works", {

  kwb.en13508.2:::mergeInspectionData(x = 1)
   kwb.en13508.2:::mergeInspectionData(x = "a")
   kwb.en13508.2:::mergeInspectionData(x = TRUE)
   kwb.en13508.2:::mergeInspectionData(x = FALSE)
   kwb.en13508.2:::mergeInspectionData(x = as.POSIXct("2018-06-03 23:50:00"))
   expect_error(
    kwb.en13508.2:::mergeInspectionData(x = 1:2)
    # x is not a list but:
#  int 1
  )
   expect_error(
    kwb.en13508.2:::mergeInspectionData(x = c("a", "b"))
    # x is not a list but:
#  chr "a"
  )
   expect_error(
    kwb.en13508.2:::mergeInspectionData(x = list(key = c("a", "b"), value = 1:2))
    # x is not a list but:
#  chr [1:2] "a" "b"
  )

})

