#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dataFrameToCsvLines_v1() works", {

  expect_error(
    kwb.en13508.2:::dataFrameToCsvLines_v1(dframe = 1, sep = 1)
    # non-numeric matrix extent
  )

})

