#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("extractInspectionData() works", {

  expect_error(
    kwb.en13508.2:::extractInspectionData(b.lines = 1, header.info = 1)
    # $ operator is invalid for atomic vectors
  )
   expect_error(
    kwb.en13508.2:::extractInspectionData(b.lines = 1, header.info = list(key = c("a", "b"), value = 1:2))
    # argument "captions" is missing, with no default
  )
   expect_error(
    kwb.en13508.2:::extractInspectionData(b.lines = list(key = c("a", "b"), value = 1:2), header.info = list(key = c("a", "b"), value = 1:2))
    # line 2 did not have 2 elements
  )

})

