#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getColumnsToRemove() works", {

  expect_error(
    kwb.en13508.2:::getColumnsToRemove(x = 1, captions = 1)
    # argument "duplicates" is missing, with no default
  )

})

