#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readEuCodedFile() works", {

  expect_error(
    kwb.en13508.2:::readEuCodedFile(input.file = 1)
    # 'con' is not a connection
  )
   expect_error(
    kwb.en13508.2:::readEuCodedFile(input.file = "a")
    # cannot open the connection
  )
   expect_error(
    kwb.en13508.2:::readEuCodedFile(input.file = c("a", "b"))
    # invalid 'description' argument
  )
   expect_error(
    kwb.en13508.2:::readEuCodedFile(input.file = list(key = c("a", "b"), value = 1:2))
    # argument 3 (type 'list') cannot be handled by 'cat'
  )

})

