#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getHeaderLinesFromEuCodedLines() works", {

  kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = 1)
   kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = 1:2)
   kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = "a")
   kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = c("a", "b"))
   kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = TRUE)
   kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = FALSE)
   kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = as.POSIXct("2018-06-03 23:50:00"))
   kwb.en13508.2:::getHeaderLinesFromEuCodedLines(lines = list(key = c("a", "b"), value = 1:2))

})

