#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getInspectionNumbers.old() works", {

  expect_error(
    kwb.en13508.2:::getInspectionNumbers.old(indices.C = 1, indices.Z = 1)
    # argument "numberOfInspections" is missing, with no default
  )
   expect_error(
    kwb.en13508.2:::getInspectionNumbers.old(indices.C = 1, indices.Z = "a")
    # non-numeric argument to binary operator
  )

})

