#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getInspectionsFromEuLines.new() works", {

  expect_error(
    kwb.en13508.2:::getInspectionsFromEuLines.new(eu_lines = 1, header.info = 1)
    # invalid 'text' argument
  )
   expect_error(
    kwb.en13508.2:::getInspectionsFromEuLines.new(eu_lines = "a", header.info = 1)
    # object 'results' not found
  )

})

