#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toEuFormat_v2() works", {

  expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = 1, mycsv = 1)
    # inspection.data is not a list but:
#  num 1
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = 1:2, mycsv = 1)
    # inspection.data is not a list but:
#  int [1:2] 1 2
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = "a", mycsv = 1)
    # inspection.data is not a list but:
#  chr "a"
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = c("a", "b"), mycsv = 1)
    # inspection.data is not a list but:
#  chr [1:2] "a" "b"
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = TRUE, mycsv = 1)
    # inspection.data is not a list but:
#  logi TRUE
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = FALSE, mycsv = 1)
    # inspection.data is not a list but:
#  logi FALSE
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = as.POSIXct("2018-06-03 23:50:00"), mycsv = 1)
    # inspection.data is not a list but:
#  POSIXct[1:1], format: "2018-06-03 23:50:00"
  )
   expect_error(
    kwb.en13508.2:::toEuFormat_v2(inspection.data = list(key = c("a", "b"), value = 1:2), mycsv = 1)
    # No such list elements: 'header.info'
# Available elements: 'key', 'value'
  )

})

